config/routes.rb
Rails.application.routes.draw do
  locale_scope = Regexp.new((I18n.available_locales = LANGUAGES.map {|lang| lang[1]}).join('|'))
  scope '(:locale)', :locale => locale_scope do
    root   'mht_frame#home', via: :all
    get    '/contact',       to: 'mht_frame#contact'
    get    '/help',          to: 'mht_frame#help'
    get    '/about',         to: 'mht_frame#about'
    get    '/news',          to: 'mht_frame#news'
    get    '/signup',        to: 'users#new'
    get    '/login',         to: 'sessions#new'
    post   '/login',         to: 'sessions#create'
    delete '/logout',        to: 'sessions#destroy'
    resources               :users
    resources               :account_activations, only: [:edit]
    resources               :password_resets,     only: [:new, :create, :edit, :update]
    resources               :projects,            only: [:index, :show, :new, :create, :edit, :update]
    resources               :buildings,           only: [:index, :show, :edit, :update]
    resources               :units,               only: [:index, :show, :edit, :update]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  before_save { email.downcase! }
  has_many :buildings
  has_many :units
  
  validates :name,         presence: true, length: { maximum: 25 },
                           uniqueness: true
  validates :address,      presence: true, length: { maximum: 255 },
                           uniqueness: true
  validates :email,        presence: true,
                           length: { maximum: 255 },
                           format: { with: VALID_EMAIL_REGEX }
  validates :no_buildings, numericality: { greater_than: 0 }
  validates :no_units,     numericality: { greater_than: :no_buildings }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.paginate(page: params[:page], per_page: 5)
  end

  def show
    @project = Project.find(params[:id])
    set_project(@project)                   # TEMP
  end

  def new
    @project = Project.new
  end

  
  def create
    ActiveRecord::Base.transaction do
      @project = Project.new(project_params)
      if @project.save
#       message = define_admin_user
        Range.new(1, @project.no_buildings).each do |num| 
          Building.create(name: num, address: @project.address, project_id: @project.id)
        end
        bld = @project.buildings.first.id
        Range.new(1, @project.no_units).each do |num| 
          Unit.create(unit_no: num, project_id: @project.id, building_id: bld)
        end
        set_project(@project) 
        flash[:success] = "#{@project.name} was successfully created. " 
        redirect_to root_path
      else
        render 'new'
      end
    end
  end
  
  def edit
    @project = Project.find params[:id]
    set_project(@project)                   # TEMP
    store_location
  end
  
  def update
 #   ActiveRecord::Base.transaction do
      @project = Project.find params[:id]
      if @project.update(project_params)
 #       message = define_admin_user
        flash[:success] = "#{@project.name} was successfully updated"
        redirect_to root_path
      else
        render 'edit'
      end
    end
#  end

  private
    def project_params
      params.require(:project).permit(:name, :email, :address, :no_buildings, :no_units)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, 'eMail of Project' %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_area :address, rows: 3, cols: 40, class: 'form-control' %>
  
  <%= f.label :no_buildings, 'No. of Buildings' %>
  <%= f.text_field :no_buildings, class: 'form-control', disabled: (!local_assigns[:create]) %>

  <%= f.label :no_units, 'No. of Units' %>
  <%= f.text_field :no_units, class: 'form-control', disabled: (!local_assigns[:create]) %>
  
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/projects/_project.html.erb
<li>
  <%= link_to project.name, edit_project_path(project) %>
  <p>
    <%= project.address %>;
    <%= project.email %><br>
    <%= project.no_buildings %> Buildings; 
    <%= project.no_units %> Units
  </p>
</li>

app/views/projects/edit.html.erb
<% provide(:title, 'Update Project') %>
<% provide(:button_text, 'Submit Changes') %>

<h1>Update Project</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>
<div class="left">
  <%= link_to 'View Buildings', buildings_path, class: 'btn btn-primary' %>
</div>
<div class="right">
  <%= link_to 'View Units', units_path, class: 'btn btn-primary' %>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<h1>List of Projects</h1>


<%= will_paginate @projects %>

<ul class="users">
  <%= render @projects %>
</ul>

<%= will_paginate %>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<% provide(:button_text, 'Create new Project') %>

<h1>New Project</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'form' , locals: {create: true}  %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <p>Name:    <%= @project.name %></p>
    <p>eMail:   <%= @project.email %></p>
    <p>Address: <%= @project.address %></p>
    <p>Buildings: <%= @project.no_buildings %></p>
    <p>Units:   <%= @project.no_units %></p>
  </div>
</div>  