config/routes.rb
Rails.application.routes.draw do
  locale_scope = Regexp.new((I18n.available_locales = LANGUAGES.map {|lang| lang[1]}).join('|'))
  scope '(:locale)', :locale => locale_scope do
    root   'mht_frame#home', via: :all
    get    '/contact',       to: 'mht_frame#contact'
    get    '/help',          to: 'mht_frame#help'
    get    '/about',         to: 'mht_frame#about'
    get    '/news',          to: 'mht_frame#news'
    get    '/signup',        to: 'users#new'
    get    '/login',         to: 'sessions#new'
    post   '/login',         to: 'sessions#create'
    delete '/logout',        to: 'sessions#destroy'
    resources               :users
    resources               :account_activations, only: [:edit]
    resources               :password_resets,     only: [:new, :create, :edit, :update]
    resources               :projects,            only: [:index, :show, :new, :create, :edit, :update]
    resources               :buildings,           only: [:index, :show, :edit, :update]
    resources               :units,               only: [:index, :show, :edit, :update]
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :project
  belongs_to :building
  
  validates :unit_no, presence: true
  validates :project_id, presence: true
  validate  :belongs_to_building
  
  private
    def belongs_to_building
      return if building_id == nil
      unless Building.find(building_id).project.id == self.project_id 
        errors.add(self.building_id.to_s, " - This building does't belong to the project")
      end
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  
  def index
    @project = Project.find(session[:project_id])
    @units = @project.units.paginate(page: params[:page], per_page: 10)
    store_location
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update(unit_params)
      flash[:success] = "Unit #{@unit.unit_no} was successfully updated."
      redirect_back_or root_path
    else
      render 'edit'
    end
  end

  private
    def unit_params
      params.require(:unit).permit(:building_id, :floor)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :unit_no %>
  <%= f.text_field :unit_no, class: 'form-control', disabled: true %>

  <%= f.label :building %>
  <%= f.select(:building_id, options_for_select(@unit.project.buildings.all.map { |b| [b.name, b.id] }) ) %>

  <%= f.label :floor %>
  <%= f.text_area :floor, class: 'form-control' %>
    
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/units/_unit.html.erb
<li>
  <%= link_to "Unit: #{unit.unit_no}", edit_unit_path(unit) %>
  <p>
    Building: <%= unit.building.name %>;
    Floor: <%= unit.floor %>
  </p>
</li>

app/views/units/edit.html.erb
<% provide(:title, 'Update Unit') %>
<% provide(:button_text, 'Submit Changes') %>

<h1>Update Unit <%= @unit.unit_no %> of <%= @unit.project.name %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/units/index.html.erb
<% provide(:title, 'Units') %>
<h1>Units of <%= @project.name %></h1>


<%= will_paginate @units %>

<ul class="users">
  <%= render @units %>
</ul>

<%= will_paginate %>

app/views/units/show.html.erb
<% provide(:title, @unit.project.name) %>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <p>Unit:     <%= @unit.unit_no %></p>
    <p>Building: <%= @unit.building.name %></p>
    <p>Floor:    <%= @unit.floor %></p>
  </div>
</div>  