config/routes.rb
Rails.application.routes.draw do
  locale_scope = Regexp.new((I18n.available_locales = LANGUAGES.map {|lang| lang[1]}).join('|'))
  scope '(:locale)', :locale => locale_scope do
    root   'mht_frame#home', via: :all
    get    '/contact',       to: 'mht_frame#contact'
    get    '/help',          to: 'mht_frame#help'
    get    '/about',         to: 'mht_frame#about'
    get    '/news',          to: 'mht_frame#news'
    get    '/signup',        to: 'users#new'
    get    '/login',         to: 'sessions#new'
    post   '/login',         to: 'sessions#create'
    delete '/logout',        to: 'sessions#destroy'
    resources               :users
    resources               :account_activations, only: [:edit]
    resources               :password_resets,     only: [:new, :create, :edit, :update]
    resources               :projects,            only: [:index, :show, :new, :create, :edit, :update]
    resources               :buildings,           only: [:index, :show, :edit, :update]
    resources               :units,               only: [:index, :show, :edit, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a><%= t('navigation.app_name') %></a>
      <%= t('navigation.by') %>
      <a href="https://il.linkedin.com/in/matiss-horodishtiano-6918802" target="_blank">
      <%= t('navigation.authםr') %>
    </a>
  </small>
  <nav>
    <ul>
      <% if ltr_or_rtl == 'ltr' %>
        <li><%= link_to t('navigation.about'),   about_path %></li>
        <li><%= link_to t('navigation.contact'), contact_path %></li>
        <li><%= link_to t('navigation.news'),    news_path %></li>
      <% else %>
        <li><%= link_to t('navigation.news'),    news_path %></li>
        <li><%= link_to t('navigation.contact'), contact_path %></li>
        <li><%= link_to t('navigation.about'),   about_path %></li>
      <% end %>
   </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light" style="background-color: #0687cc;">
  <div class="container">
    <a class="navbar-brand">
      <%= link_to t('navigation.app_name'), root_path, id: "logo" %>
    </a>
    <nav navbar-light>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <% if ltr_or_rtl == 'ltr' %>
        <ul class="nav navbar-nav navbar-right collapse navbar-collapse" 
            id="bs-example-navbar-collapse-1">
          <li><%= link_to t('navigation.home'),  root_path %></li>
          <li><%= link_to t('navigation.help'),  help_path %></li>
          <% if logged_in? %>
            <li><%= link_to t('navigation.users'), users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t('navigation.account') %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('navigation.profile'), current_user %></li>
                <li><%= link_to t('navigation.settings'), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t('navigation.logout'), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t('navigation.login'), login_path %></li>
          <% end %>
          <li>  
            <%= form_tag root_path, class: 'locale' do %>
              <%= select_tag 'set_locale',
                  options_for_select(LANGUAGES, I18n.locale.to_s),
                  onchange: 'this.form.submit()' %>
              <%= submit_tag 'submit', id: "submit_locale_change" %>
            <% end %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left collapse navbar-collapse" 
            id="bs-example-navbar-collapse-1">
          <li>  
            <%= form_tag root_path, class: 'locale' do %>
              <%= select_tag 'set_locale',
                  options_for_select(LANGUAGES, I18n.locale.to_s),
                  onchange: 'this.form.submit()' %>
              <%= submit_tag 'submit', id: "submit_locale_change" %>
            <% end %>
          </li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t('navigation.account') %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('navigation.profile'), current_user %></li>
                <li><%= link_to t('navigation.settings'), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t('navigation.logout'), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <li><%= link_to t('navigation.users'), users_path %></li>
          <% else %>
            <li><%= link_to t('navigation.login'), login_path %></li>
          <% end %>
          <li><%= link_to t('navigation.help'),  help_path %></li>
          <li><%= link_to t('navigation.home'),  root_path %></li>
        </ul>
      <% end %>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir=<%= ltr_or_rtl %> lang=<%= I18n.locale.to_s %> >
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <% if ltr_or_rtl == 'ltr' %>
      <%= stylesheet_link_tag 'mht_frame', media: 'all' %>
    <% else %>
      <%= stylesheet_link_tag 'mht_frame-rtl', media: 'all' %>
    <% end %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
    <%= javascript_pack_tag 'locale_switcher', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>